### ISSUE TITLE
Okay to fork, modify, and distribute?

### ISSUE THREAD

**Issue by ammmze** [BlueCocoa/EventEmitter#3]
I'm looking to use this (along with your Functor) library in a project using [platformio](https://platformio.org). So I'd like to get these published on the platformio registry. Though in my scenario I had to modify the `Functor` little because I couldn't compile with the `typeid` stuff.

So given the only license specified on these is "All rights reserved", I'm looking for permission to fork these 2 projects, potentially modify them, and publish them to platformio.

**Comment by BlueCocoa** [comment]
Yes, please feel free to use them. I've added MIT license.

**Comment by ammmze** [comment]
👍 I appreciate it
